version: '3.9'

services:
  server:
    image: boardscape:1.0
    build: 
      context: ./server
      dockerfile: Dockerfile
    env_file: .env
    hostname: ${SERVER_HOST}
    ports: 
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - ./server:/server
      - server-v-node-modules:/server/node_modules
    depends_on:
      database:
        condition: service_healthy
    
  database:
    image: boardscape_db:1.1
    build: 
      context: ./database
      dockerfile: Dockerfile
    env_file: .env
    hostname: ${POSTGRES_HOST}
    ports: 
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - database-v:/var/lib/postgresql/data
    command: "-p ${POSTGRES_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -p ${POSTGRES_PORT} -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      start_period: 0s
      interval: 5s
      timeout: 5s
      retries: 5


volumes:
  server-v-node-modules:
    name: "server-v-node-modules"
  database-v:
    name: "database-v"